### ISSUE TITLE
updates - adjustment to secondary navbar 

### ISSUE THREAD

**Issue by noelelusano** [EvictionLab/eviction-lab-website#100]
768+
![image](https://user-images.githubusercontent.com/6036323/37786849-e7798cea-2dba-11e8-9fb9-7bf0f0ddc68b.png)
• please adjust height of .subnav to 64px to match what is on rankings, with 32px between list items - see rankings https://staging.evictionlab.org/rankings/#/evictions

-------
320
![image](https://user-images.githubusercontent.com/6036323/37787800-1138f046-2dbd-11e8-9eef-32399a46dac4.png)
• height of .subnav shrinks to 40px on 320 with 24px between list items

**Comment by Lane** [comment]
Working on fixing this up.  @james-minton and @noelelusano, for cases where subnav items wrap to a second line, what should I do?  Does stacking them like we're doing for the rankings page work?

![image](https://user-images.githubusercontent.com/21034/38425058-1450f5ee-3970-11e8-974e-2f741138285a.png)

**Comment by james-minton** [comment]
Thanks Lane, there's some code on WEM that switches to a dropdown on mobile
-- could be applied here
