### ISSUE TITLE
style fixes for site pages excluding map/rankings

### ISSUE THREAD

**Issue by noelelusano** [EvictionLab/eviction-lab-website#101]
The issues below reference the most recent Sketch file that's been uploaded to https://app.box.com/folder/46344370140 – everything needed should be in this file, if not let me know.

-----

# **Margins**
• ensure there is consistent whitespace between secondary nav/breadcrumbs and content across pages

**--------------------- DONE ---------------------**

![image](https://user-images.githubusercontent.com/6036323/37792019-dcf6c4ec-2dc7-11e8-9f4f-9527ec5b205a.png)
**about**

![image](https://user-images.githubusercontent.com/6036323/37792055-faf12abe-2dc7-11e8-85d0-a005be54108c.png)
**updates**

-----

# **Social Share**
• i don't see instances of social share outside of map & rankings: if we can't do the sticky social share functionality, can we implement the same styling on social elements as currently exists on [rankings](https://staging.evictionlab.org/rankings/#/evictions)? the sketch file is [here](https://app.box.com/folder/46344370140); go to "Symbols - Share Lockup"

![image](https://user-images.githubusercontent.com/6036323/37793482-120cc20e-2dcc-11e8-8d19-5f51caf7543d.png)

**--------------------- DONE ---------------------**

-----

# **Splash Screen**
![image](https://user-images.githubusercontent.com/6036323/37794668-62e482cc-2dcf-11e8-9199-74b551e4b73d.png)
• please ensure that buttons font/style matches most recent file [here](https://app.box.com/folder/46344370140) (see "Symbols - Buttons")
• remove containing boxes from social icons, ensure each icons is the same size as the icon in the hamburger menu
• H1 "We're unpacking..." should be aligned with the logo
**--------------------- DONE ---------------------**
  
• possible to cut down the text here by at least one line?

-----

# **Newsletter Signup**
• change font on "Submit" button to: 
**768+**  _font-family: GTEestiDisplay-Bold; font-size: 14px; color: #FFFFFF; letter-spacing: 1px;_
**320**  _font-family: GTEestiDisplay-Bold; font-size: 10px; color: #FFFFFF;
letter-spacing: 0.54px;_

• change size of "Submit" button to: 
**768+** 64px  / **320** 40px
 if input fields are not the same, please synchronize those

• ensure that fonts used on this piece sync up to the style guide for respective breakpoints (style guide was completed after newsletter signup piece was submitted)

• change color of text in input field to #fff for legibility

-----

# **Links**
• remove underlines from links, as they are already red, and follow any instance of "read more" or "learn more" with the right carat that exists on current breadcrumb (see below)

• remove Gt Eesti Display from all links (e.g. "Read More") so that all links under Updates which are not part of the navigation are Akkurat - do not need to be bolded if followed with right carat

**--------------------- DONE ---------------------**

-----

# **Arrows/Carats**
• update all down arrows (e.g. for each question on FAQ and Methods) - find final icons at most recent file [here](https://app.box.com/folder/46344370140) - go to "Pages: Finalized Icons" - down and up arrows should be sized to 13x13 px for 768+ / 10x10 px for 320

• right carat in breadcrumb ("Updates **>** Blog") needs to be aligned to surrounding text's center
![image](https://user-images.githubusercontent.com/6036323/39064610-fa2482ca-4483-11e8-8fd5-9cfb8c45e425.png)

• use the same carat in breadcrumb (but brand red) for any "read more >" or "learn more >" link 

• update carat in "about" modal
![image](https://user-images.githubusercontent.com/6036323/37799207-3d5b100e-2ddc-11e8-9cda-1e06b29b502a.png)

-----

# **Updates Page**
• "Read More" links look isolated from associated text snippet. please shorten that gap to 16px or 24px at your discretion

• on 768+ breakpoints, colored category links (Blog, Research, Media etc.) next to author attribution look isolated from content. please shorten this gap to 16px or 24px at your discretion

-----

# **About Page**
• I envisioned that when scrolling the page, the active/selected links in subnav would reflect where user has scrolled to on page, for example if scrolled down to "Our Work", then "Our Work" would be highlighted in the subnav (currently it is only highlighted if the subnav is specifically selected)

• can we use the established H4 for quote attribution in the CMS? ("—Matthew Desmond" is set in the same font and size - if we are locked with that constraint would prefer not to use a quote here, as it looks unintentional)

• move "Eviction functions as a cause, not just a condition of poverty." / second pull quote into the same position as the 1st and 3rd panels - starting at the top of the 2nd panel along with the header. the positioning does not look good across different breakpoints, would look cleaner if consistent with 1st and 3rd panels.

• Eviction Lab Team bios arrow icon -  update arrow to the right arrow [here](https://app.box.com/folder/46344370140) - 16x16 px for all breakpoints

• increase spacing between team bio pic circles as in comp in increments of 8 px - if issues showing four on one line change to three on one line. center team bio pics so that one team member under one category or on one line does not make the page look off-kilter.

• update "close" button on team bio modal window - see final icons [here](https://app.box.com/folder/46344370140)  - example placement is on lane's walkthrough modal

• on team bio modal window, modal should float in the center of the viewport on 768+ breakpoints

-----

# **Events Page**
• **.div.event-deets**: 768 - padding: 1.6rem 2.6rem / 1440+ - padding: 1.6rem 3.6rem

• add carat to "Read More" 

• treat "Read More >" in the same style and positioning relative to main content block as on "Updates" landing page

• on 320 breakpoint, please remove letter-spacing from body text

• change dimensions of "date" and "website" icons to 22x22 px / add 40px spacing between those icons and the date and website detail text

• minimize the — in the "Date—Date" to an en dash rather than em dash

![image](https://user-images.githubusercontent.com/6036323/37792789-0189b5ec-2dca-11e8-88c1-cb23cb155d35.png)
• can we constrain the abbreviation of months to 320?

• shorten gap between number and month name to 16px

-----

# **Event Post Page**
![image](https://user-images.githubusercontent.com/6036323/37788313-4eb2e3ea-2dbe-11e8-9739-5e42f9262169.png)
• can we do a display:none on the redundant date in the header?

-----

# **Headers**
![image](https://user-images.githubusercontent.com/6036323/37791614-e4fd85aa-2dc6-11e8-8005-57c7e207e94b.png)
![image](https://user-images.githubusercontent.com/6036323/37791620-eb5343b8-2dc6-11e8-8a63-9ba5412838ee.png)
• ensure that all headings have the same font size, stroke weight and padding between the heading element and the bottom of the subnav: 

• headings: 768+ -  _font-family: GTEestiDisplay-Bold; font-size: 16px; color: #434878; letter-spacing: 0.9px;_ 320 - _font-family: GTEestiDisplay-Bold; font-size: 13px; color: #434878; letter-spacing: 0.7px;_ 

• stroke weight: 768+: 5px / 320: 3px

-----

# **Updates to Typography**
• all subcopy for 768 breakpoint sized to 1.175rem - apply this instances of subcopy in newsletter signup and footer

• remove letterspacing from all author attribution - Akkurat should no longer have any letter-spacing anywhere outside of map and UI
![image](https://user-images.githubusercontent.com/6036323/37792122-2e5dbc50-2dc8-11e8-8f9e-79db7a551c5e.png)

-----

# **Updates to Splash Page - added 20180402**
• please check font size of H1s based on the sketch file. looks like letter-spacing is set to 2 when it should be 1 for 

-----

# **Updates to Social Share - added 20180405**
• there is a shadow applied to the icons here, please remove
![image](https://user-images.githubusercontent.com/6036323/38395676-f7fa9314-38e8-11e8-9291-038d0edeb27d.png)

-----

# **Added 20180420**
• it looks like a fake italic is being used for Akkurat italics instead of "Akkurat Italic" itself
![image](https://user-images.githubusercontent.com/6036323/39064740-67bc0114-4484-11e8-9d7e-6edd9c762222.png)
• about us - please change the "position" text to #737373, including in the associated popup/modal
![image](https://user-images.githubusercontent.com/6036323/39064781-83b0f302-4484-11e8-87f8-0a0f20a55249.png)
• about us modal - get rid of the horizontal rule at bottom of modal
• about us modal - ensure the proper close icon is used
![image](https://user-images.githubusercontent.com/6036323/39064816-a958c1ac-4484-11e8-80b2-581341be4f60.png)
• about us - do we need the "go to section" still in the navigation? thought we were getting rid of this with exception of 320 viewport

• pictorial menu - images appear blurry (macbook pro, 1440)
![image](https://user-images.githubusercontent.com/6036323/39064939-0ed1a2d8-4485-11e8-8f9b-9027b58f54a7.png)

• newsletter signup in relation to footer below it - looks like left margins do not align for 1440 and 1024, can you adjust the margins and widths of containers so that things are more in balance?
![image](https://user-images.githubusercontent.com/6036323/39065234-f4a38f42-4485-11e8-975a-6eb7f3aa8ac6.png)

**Comment by noelelusano** [comment]
@james-minton 
just noting here that all medium greys on non map/rankings pages need to change to #737373 as per the contrast discussion with Lane. this includes color of social icons. if you're sourcing the same svg icons as Lane should be a quick fix

**Comment by james-minton** [comment]
@noelelusano working on newsletter signup now. Couple of questions:

> • change size of "Submit" button to: 768+ 64px / 320 40px

What exactly are the 64px and 40px numbers referring to?

> • ensure that fonts used on this piece sync up to the style guide for respective breakpoints (style guide was completed after newsletter signup piece was submitted)

Here's what that looks like for 768-1023:

<img width="980" alt="screen shot 2018-05-02 at 10 09 03 pm" src="https://user-images.githubusercontent.com/33635008/39557530-64e6f792-4e56-11e8-8fd6-9f86efe02c4d.png">

Wanted to make sure this is what you want here.

**Comment by noelelusano** [comment]
@james-minton sorry, just seeing this - need to get github notifications sent to my email.

i've updated the mockups here https://app.box.com/s/l798p7avquzekza8lhdxmr807nbjb95b - go to "Newsletter Signup" within the file.

changes i've made:
• for 768+ all orange buttons and form fields for this piece are changed from 56px to 64px height.
• for 1440+ the container for all newsletter elements has been constrained to 720px. 
• copy has been changed from "Submit" to "Sign Up" as per best UX practices for conversion

![image](https://user-images.githubusercontent.com/6036323/39944280-f129f7e8-551a-11e8-8744-1b588bdc945a.png)
let me know if any issues
