### ISSUE TITLE
remove drop shadow from stacked primary and secondary nav on scroll

### ISSUE THREAD

**Issue by noelelusano** [EvictionLab/eviction-lab-website#103]
![image](https://user-images.githubusercontent.com/6036323/37803481-34a0af2c-2dec-11e8-8123-72ecdf2a7813.png)
if possible, remove drop shadow from primary nav when the two navigations are stacked like this

see https://github.com/EvictionLab/eviction-maps/issues/674 for shadow treatments

**Comment by james-minton** [comment]
Good call. Since every page with a subnav has a hero below the header, I don't see the need for a drop shadow there (it's not really visible when overlaid on the image) so I'll just drop it for those pages.
