### ISSUE TITLE
Create "buy" modal for Evicted book

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#107]

**Comment by james-minton** [comment]
Matt wants the "buy the book" button on Why Eviction Matters to mimic the one here: http://evictedbook.com/books/evicted-tr

Or, at the very least by launch, have that button go _somewhere_ (e.g. Amazon) where you can buy it.

There are some publisher affiliate codes in the links on the other book site; I don't think we need to duplicate that right now. Will have to check with the publisher but for now, just direct links to booksellers works.

You could use existing styles here, and / or I can do a pass afterward on your code.

**Comment by pjsier** [comment]
Feel free to re-open, but assuming this is done after the last styling update
