### ISSUE TITLE
Add footer elements

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#114]
The footer is going to be doing more duty. 

- "Get the Data" link -- @Lane and @pjsier, can we go with the strategy: "make it so you can advance to the data if you just enter something with an @ (valid email address syntax)?"
Suggested copy: "Enter your email address below to receive the raw eviction data for the United States. In return, we'll send occasional alerts about updates to the data."
- Credits link? (E.g. for photos) (@noelelusano  -- we def. need to credit photographers, as we're getting a number of these for free on that condition)
- Research wants a fine print disclaimer about the data not being comprehensive, etc. there. Language TK. Can we block out some space for it?
- Say something in the footer like "made possible by Mapbox?" With their logo? Or just a credit to them on the credits page?
- Add another link: Data Merge Application
- And another: to possible company site (e.g. site by " ________ ")

**Comment by Lane** [comment]
@james-minton, for point #1, no we can't if we want it to sign them up for data updates via mailchimp.  The form is submitted to mailchimp via a post request, meaning the browser navigates to a mailchimp hosted page.  Mailchimp takes the email address and validates it and shows a page in response.  I think we can set up a custom landing page on mailchimp, but that will need to be looked into further.

**Comment by james-minton** [comment]
Ok ... if grabbing the email address by the method I described and adding it to our list somehow (in a way that does not require the mailchimp form? Is that possible?) is not an option, let's figure out the next best option.

**Comment by Lane** [comment]
I think our only option is to go with a custom landing page that has a link to the data.  Though that means even people that only subscribed to the newsletter will be directed there too.

https://kb.mailchimp.com/lists/signup-forms/design-and-host-your-own-thank-you-pages

**Comment by james-minton** [comment]
@lane @noelelusano : adding another link to the above: _Data Merge Application_

Also: have requested footer disclaimer language. Should be forthcoming soon.
