### ISSUE TITLE
Add FAQ question for Maryland

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-lab-website#118]
Maryland filings are significantly higher than everywhere else.  Matt says this is because Maryland has a different filing process than everywhere else.  

Eviction process in most states:
1. Eviction notice is issued by landlord (not tracked)
2. Person does not leave, eviction court date is set (tracked)
3. Eviction judgement is made (tracked)

In Maryland, step number 1 in the process **is** tracked and counted as an eviction filing.

**Comment by james-minton** [comment]
Addressed by a Research in FAQs
