### ISSUE TITLE
Update modal styles

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#121]
Make About Us modals "swipeable" -- left or right swipe = previous / next bio.

Also add style for "dismiss" button.

**Comment by james-minton** [comment]
Pat, would you be able to tackle this? 

For the second part, I want to have the same "dismiss" button style as our other modals.

**Comment by pjsier** [comment]
Is it fair to say the swiping is lower priority? Checking because that could take a good amount more time than just updating the styles

**Comment by james-minton** [comment]
For sure, file under "nice to have" / post-launch

**Comment by pjsier** [comment]
Great, I'll split that out from the general style updates in this issue then

**Comment by pjsier** [comment]
Closed by #145
