### ISSUE TITLE
Make fixed social share sidebar stop at footer

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#124]
Hi @pjsier , I have a newly implemented set of social buttons on staging/why-eviction-matters , set to `position: fixed`. Would like to set this share box so it becomes `absolute` or whatever once it hits the footer, and doesn't overlap into it.

Thinking adding a class through jQuery is the way to go, but not sure how to trigger that when it hits the footer. Using a pixel offset to trigger it doesn't seem to make sense, as the height of the page will vary and I want to implement this on a few pages. Unless we can offset it from the bottom of the page?

Hoping there's an easy solution.

**Comment by pjsier** [comment]
I think the easiest implementation would just be setting `position: sticky` and then something like `top: 200px`, which would do what you're describing. It could fall back to `position: fixed` for IE, and it seems like it's not essential functionality to replicate there. Would this display at all on mobile?

**Comment by pjsier** [comment]
Looks like this was fixed in #191
