### ISSUE TITLE
Open accordion tab when arrived at from external link

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#130]
Hi @pjsier , I'll need to link to and between accordion tabs, and obviously it would be nice if those opened automatically when you arrive. Looks like this requires JS, but seems pretty simple. Would you be able to handle?

**Comment by james-minton** [comment]
Again, for testing, I added a `name` ("map-embed") to the `<a>` tag for the specific FAQ question about map embeds ... I'll be adding `a name`s to all the questions shortly.

**Comment by pjsier** [comment]
In this case, I think it's more important that they have an `id` attribute, not sure that links support `name`

**Comment by james-minton** [comment]
We've been using each section's `name` as a target for the subnav, which works ...

And each link does have an id, but it's a number (e.g. 110, 120, etc.). Which I thought wasn't allowed? (Classes can start with numbers, but id's can't?) But that's how J set it up, and it works, so to keep things simple I just use the `weight` parameter for each question / answer as the id.

**Comment by pjsier** [comment]
Ah I forgot that we're preventing default browser behavior here, I remember the setup now

**Comment by Lane** [comment]
Sorry to jump in on this, but we should definitely avoid using both ID's and classes that start with a number.  It violates the W3C specification:

> In CSS, identifiers (including element names, classes, and IDs in selectors) can contain only the characters [a-zA-Z0-9] and ISO 10646 characters U+00A0 and higher, plus the hyphen (-) and the underscore (_); they cannot start with a digit, two hyphens, or a hyphen followed by a digit

**Comment by pjsier** [comment]
I'll clean that up in this PR, we can just add a prefix to it

**Comment by james-minton** [comment]
Yeah was thinking same, thanks
