### ISSUE TITLE
Older browser testing

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#141]
e.g. IE 11, older (but still supported versions of ) Safari / Chrome

I still have a lot to do on WEM, About Us, and Help + Methods, but if you see anything seriously amiss in these browsers that looks different from the most recent Chrome, please let me know (or feel free to fix!).

E.g. some older browsers aren't responding as well to `grid` and `flex`, so I've tried to add fallbacks, but not sure if I've caught everything. Also probably need to add `ms-grid` in there, and `-webkit` for many elements too.

**Comment by Lane** [comment]
I'm going to do a pass on IE11, branching off of your browser compatibility branch @pjsier

**Comment by pjsier** [comment]
@Lane works for me! I took an initial look at it, and the biggest issue I ran into was `display: grid`. Converting to the `-ms` prefixes made it worse

**Comment by james-minton** [comment]
If we need to do a flex equivalent instead, I'm on board as long as it looks basically the same

**Comment by Lane** [comment]
IE11 should be good, aside for #165, but leaving that as a low priority issue for now.
