### ISSUE TITLE
Birth date on form?

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#221]
What could this mean?

Please text or call me at [----] Thanks! I’m with HUD, the U.S. Department of Housing and Urban Development in the [----]. Perhaps we could work together somehow.  By the way, I couldn’t get past your form asking for birth month and day because it would only accept 2 digits and that’s all.  Please text or call me at [----] Thanks! Keep up the Great Work.
--

**Comment by Lane** [comment]
Removed birth date field
