### ISSUE TITLE
Switching to Spanish on "Updates" redirects to empty page

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-lab-website#227]
- Go to the updates page here: https://evictionlab.org/updates/
  - Switch the language to Spanish

The page is redirected to: https://evictionlab.org/es/updates/ which is an empty page.

**Comment by james-minton** [comment]
Thanks for catching -- at one point, #1 was the default state, or no? I recall on launch there was no translation option available for Updates. Not sure what changed. In any case I think we should remove it, even at the cost of users having to re-toggle the switch; I don't think we should tease a Spanish translation we don't actually have.
