### ISSUE TITLE
Create interactives for "Houston ISD" blog post

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#604]
Blog post text (with figures) attached.

We need to 

- [ ] Adapt the existing bar chart component to display a distribution/histogram (as shown in the attached doc)
- [ ] Create choropleth map (styled like ETS maps) with toggle to switch between eviction filing counts and eviction filing rate maps

Notes from the Lab:

> I attached the shapefiles (Elementary1718.zip) and the data (HISD Filings by Elementary School Zone (Both Years).csv). I join the data to the shapefiles by ‘Code’, the first column for both files. I just wanted to flag that there’s a school code 058 that often gets turned to 58 and then it would fail to join; I found that it works best when I specify the code column to be imported as a string. Otherwise, there are 4 columns in the csv file: Code, school, totalfilings and filingrate. School is the name of the school, totalfilings is the number of eviction filings, and filingrate is the eviction filing rate. Please let me know if you have any questions!

[HISD_brief_20210512.docx](https://github.com/EvictionLab/eviction-lab-website/files/6547753/HISD_brief_20210512.docx)
[Elementary1718.zip](https://github.com/EvictionLab/eviction-lab-website/files/6547755/Elementary1718.zip)
[HISD Filings by Elementary School Zone (Both Years).csv](https://github.com/EvictionLab/eviction-lab-website/files/6547756/HISD.Filings.by.Elementary.School.Zone.Both.Years.csv)

**Comment by Lane** [comment]
thanks, breaking these down into subtasks:

## Histogram


- [ ] create histogram module (`Elab.Histogram`) in `themes/evictionlab/assets/charts/histogram.js`.  in this file, use the [chart builder](https://github.com/EvictionLab/eviction-lab-website/blob/development/themes/evictionlab/assets/charts/chart-builder.js) (similar to [bar chart module](https://github.com/EvictionLab/eviction-lab-website/blob/development/themes/evictionlab/assets/charts/bar-chart.js)) (see [d3 histogram example](https://observablehq.com/@d3/histogram))
- [ ] add the histogram module to the [loaded scripts when `charts` is set in the blog post front matter](https://github.com/EvictionLab/eviction-lab-website/blob/63b9623d8fc24b6bebafdc74b7f82bf44026886e/themes/evictionlab/layouts/partials/footer.html#L161)
- [ ] add a linear scale x axis function (addAxisX) similar to [addAxisY](https://github.com/EvictionLab/eviction-lab-website/blob/development/themes/evictionlab/assets/charts/chart-builder.js#L987) to use for the histogram X axis
- [ ] shape csv data into histogram bins
- [ ] create shortcode that accepts props for csv file, number of bins for histogram (see [bar chart shortcode](https://github.com/EvictionLab/eviction-lab-website/blob/development/themes/evictionlab/layouts/shortcodes/bar-chart.html))
- [ ] add docs for bar chart shortcode to [shortcode docs](https://github.com/EvictionLab/eviction-lab-website/blob/development/docs/shortcodes.md)

## Map

- [ ] create mapbox module (`Elab.Mapbox`) in `/themes/evictionlab/assets/maps/mapbox.js` ( use the [eviction tracker map module as a starting point](https://github.com/EvictionLab/eviction-lab-website/blob/development/themes/evictionlab/assets/eviction-tracking/app.js#L1415))
- [ ] conditonally load mapbox library on the page when `mapbox` is in the `scripts` frontmatter (similar to [how chart scripts are loaded](https://github.com/EvictionLab/eviction-lab-website/blob/63b9623d8fc24b6bebafdc74b7f82bf44026886e/themes/evictionlab/layouts/partials/footer.html#L161))
- [ ] convert district shapefiles to geojson using mapshaper.org
- [ ] create a shortcode that accepts geojson shape file and CSV data file and renders the map using the mapbox module that was created.  (similar to the [shortcode created for eviction tracker maps](https://github.com/EvictionLab/eviction-lab-website/blob/development/themes/evictionlab/layouts/shortcodes/report_map.html))
- [ ] add docs for mapbox shortcode to [shortcode docs](https://github.com/EvictionLab/eviction-lab-website/blob/development/docs/shortcodes.md)

## Notes

eviction lab is not setup to transpile ES2015/ES6 code.  all code written should work on IE11.  this means:
  - do not use arrow functions, default params, const/let, or ES2015 features
