### ISSUE TITLE
Add website translations

### ISSUE THREAD

**Issue by Lane** [EvictionLab/eviction-lab-website#62]
Implement a way to switch languages on the website.

**Comment by pjsier** [comment]
Content from other issue here

> It looks like the translations configuration here is probably the way to go https://gohugo.io/content-management/multilingual/#configure-languages
> This way, we can just configure English to sit at / and other translations will reside at their respective codes like /es

**Comment by james-minton** [comment]
Closing -- sorry, I duplicated this in #119. Will let that one take precedence.
