### ISSUE TITLE
Conform blog social share links to map/rankings implementation

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#73]
I.e. make them function the same as on those pages. Could you help with this @pjsier ? No rush.

Twitter share could just be "{{ .Title }}, via @evictionlab {{ .Permalink }}"

Example page: /updates/blog/2018-02-18-latest-post9/
Implicated files: /site/layouts/single.html

Working in cms-dev should be fine. Thanks!

**Comment by pjsier** [comment]
I’ll branch off of cms-dev, but this should be pretty straightforward to implement

**Comment by james-minton** [comment]
Thanks @pjsier this is cool, but I'd gotten used to the smaller popups, as we have them in the map, for social share rather than full tabs as done here. Is there any way to make that happen? (I see some other sites use the full tab treatment, so it's not a big deal, but would be great to do it the same site-wide if possible)

**Comment by pjsier** [comment]
Just updated!

**Comment by james-minton** [comment]
One thing I just noticed: Facebook pops up and rapidly disappears for me (Chrome / Macbook). No idea what's happening there.

**Comment by pjsier** [comment]
That's because of the error I mentioned in the PR. It'll be fixed once we adjust the `baseURL`
