### ISSUE TITLE
Next and Previous links to posts containing a specific parameter

### ISSUE THREAD

**Issue by james-minton** [EvictionLab/eviction-lab-website#77]
Hey @pjsier , before I spin my wheels too much more on this --

I have a parameter called "contenttype" for all blog posts. There are 2 "contenttypes": "events" and "updates." I set up this differentiation because I wanted to split event posts from regular blog posts and not have those streams mix.

As I currently have it in single.html, the functions .Next and .Prev are used to pull up the next and previous posts. But I want to refine this to only show next and previous posts for the "updates" contenttype, not "events." Currently "events" are being mixed in, because .Next and .Prev are global for all posts. 

(There's also .NextInSection, but that filters things too narrowly -- it only shows content housed in the current folder, e.g. blog, media, or research; I want to encompass all those folders but exclude events.)

Can you help me refine which posts are shown here?

**Comment by pjsier** [comment]
From what I can tell, this isn't currently supported. I looked into some old issues around it, and it looks like `.NextInSection` is what is typically suggested. I guess I'm not sure why events are more different from blog posts than research is?

**Comment by james-minton** [comment]
Whole different content, whole different styling. Events are just short recitations of fact about an event (time / date / etc.). If I want to read informative articles about eviction, I don't necessarily want to have to page through those.

**Comment by pjsier** [comment]
That makes sense, but it seems like that could also apply to media and research? Even if the styling isn't different, the content is

**Comment by james-minton** [comment]
Differences are fewer with those. Sorry but I don't really want to argue this conceptually, just want to figure something out. I see here that there's a way of working in a variable to the "With" function ... is that a possible angle? https://gohugo.io/functions/with/

**Comment by james-minton** [comment]
So e.g. current code is

     `   {{ with .Next }}
         <a href="{{ .Permalink }}">{{ .Title }}</a>
          {{ end }}`

If we could declare a variable for `Params.contenttype "updates"` , could that be associated with (and narrow the scope of) the "with" function?

Don't know if this is wildly off the mark or what, but thanks for entertaining it.
