### ISSUE TITLE
Extra margin for header on mobile widths

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-lab-website#90]
Looks like this is because the header height shrinks on mobile, so we need the top margin to shrink as well

<img width="557" alt="screen shot 2018-03-09 at 8 33 49 am" src="https://user-images.githubusercontent.com/8291663/37212417-b2288564-2374-11e8-806f-a8662923b587.png">

**Comment by james-minton** [comment]
Thanks Pat, I'm on this - i had fixed it before but then someone's merge overwrote it.

**Comment by pjsier** [comment]
Looks like this is fixed, closing
