### ISSUE TITLE
Set custom 404 page on S3 bucket

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-lab-website#94]

**Comment by pjsier** [comment]
@james-minton this is a small thing, but right now it looks like our 404.html page is blank. It doesn't matter to me what's in it, but are we planning on filling in that file?

**Comment by james-minton** [comment]
Yeah we should ... is it worth asking Noele for a design for this?

**Comment by pjsier** [comment]
Probably not worth it for now given the other stuff we've got going on. Maybe just plug in a default layout with the typical "Sorry, page not found" message?

**Comment by james-minton** [comment]
Sure thing, maybe we can circle back on it after launch. Can we use our usual fonts, though?

**Comment by pjsier** [comment]
Works for me, and I don't see why not
